import { useState } from "react";
import { useData } from "../context/DataContext";
import { BULAN, SIMPANAN_POKOK, SIMPANAN_WAJIB, TAHUN_AKTIF, fmt } from "../config";
import S from "../styles";

export default function Anggota() {
  const { members, activeMembers, simpananPokok, simpananWajib, currentMonth, hitungSHU, addMember, updateMember, toggleStatus, bayarPokok, toggleWajib } = useData();
  const [search, setSearch] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [editM, setEditM] = useState(null);
  const [detail, setDetail] = useState(null);

  const tPokok = Object.values(simpananPokok).filter(s => s.lunas).length * SIMPANAN_POKOK;
  const tWajib = Object.values(simpananWajib).reduce((s, a) => s + a.length * SIMPANAN_WAJIB, 0);
  const filtered = members.filter(m => m.nama.toLowerCase().includes(search.toLowerCase()) || m.id.toLowerCase().includes(search.toLowerCase()));

  return (<>
    <div style={{ display: "flex", gap: 8, marginBottom: 12 }}><div style={S.statCard}><div style={{ fontSize: 11, color: "#64748B" }}>Anggota aktif</div><div style={{ fontSize: 20, fontWeight: 700, color: "#2563EB" }}>{activeMembers.length}</div></div><div style={S.statCard}><div style={{ fontSize: 11, color: "#64748B" }}>Total simpanan</div><div style={{ fontSize: 20, fontWeight: 700, color: "#16A34A" }}>Rp {fmt(tPokok + tWajib)}</div></div></div>
    <input style={{ ...S.input, marginBottom: 12 }} placeholder="Cari nama atau nomor..." value={search} onChange={e => setSearch(e.target.value)} />
    {filtered.map(m => (<div key={m.id} style={{ ...S.card, display: "flex", alignItems: "center", gap: 10, cursor: "pointer" }} onClick={() => setDetail(m)}><div style={S.avatar(m.status === "aktif" ? "#2563EB" : "#94A3B8")}>{m.nama.split(" ").map(n => n[0]).join("").substring(0,2)}</div><div style={{ flex: 1 }}><div style={{ fontSize: 14, fontWeight: 500 }}>{m.nama}</div><div style={{ fontSize: 12, color: "#64748B" }}>{m.id} · Poin: {m.poin||0}</div></div><span style={S.badge(m.status)}>{m.status}</span></div>))}
    <button style={S.fab} onClick={() => setShowForm(true)}>+</button>

    {showForm && (() => { const F = () => { const [f, setF] = useState({ nama: "", alamat: "", hp: "" }); const [err, setErr] = useState(""); return (<div style={S.modal} onClick={() => setShowForm(false)}><div style={S.modalContent} onClick={e => e.stopPropagation()}><div style={S.modalHeader}><span style={{ fontSize: 16, fontWeight: 600 }}>Tambah anggota</span><button onClick={() => setShowForm(false)} style={S.closeBtn}>✕</button></div><div style={{ display: "flex", flexDirection: "column", gap: 10 }}><input style={S.input} placeholder="Nama lengkap" value={f.nama} onChange={e => { setF({...f, nama: e.target.value}); setErr(""); }} /><input style={S.input} placeholder="Alamat" value={f.alamat} onChange={e => setF({...f, alamat: e.target.value})} /><input style={S.input} placeholder="No. HP" value={f.hp} onChange={e => setF({...f, hp: e.target.value})} />{err && <p style={{ color: "#DC2626", fontSize: 12, margin: 0 }}>{err}</p>}<button style={S.btn()} onClick={() => { if (!f.nama.trim()) { setErr("Nama wajib"); return; } addMember(f); setShowForm(false); }}>Simpan</button></div></div></div>); }; return <F />; })()}

    {editM && (() => { const F = () => { const [f, setF] = useState({ nama: editM.nama, alamat: editM.alamat, hp: editM.hp }); return (<div style={S.modal} onClick={() => setEditM(null)}><div style={S.modalContent} onClick={e => e.stopPropagation()}><div style={S.modalHeader}><span style={{ fontSize: 16, fontWeight: 600 }}>Edit anggota</span><button onClick={() => setEditM(null)} style={S.closeBtn}>✕</button></div><div style={{ display: "flex", flexDirection: "column", gap: 10 }}><input style={S.input} placeholder="Nama" value={f.nama} onChange={e => setF({...f, nama: e.target.value})} /><input style={S.input} placeholder="Alamat" value={f.alamat} onChange={e => setF({...f, alamat: e.target.value})} /><input style={S.input} placeholder="No. HP" value={f.hp} onChange={e => setF({...f, hp: e.target.value})} /><button style={S.btn()} onClick={() => { updateMember({ ...editM, ...f }); setEditM(null); }}>Simpan</button></div></div></div>); }; return <F />; })()}

    {detail && (() => { const m = members.find(x => x.id === detail.id)||detail; const pokok = simpananPokok[m.id]; const wajib = simpananWajib[m.id]||[]; const shu = hitungSHU(m.id); return (<div style={S.modal} onClick={() => setDetail(null)}><div style={S.modalContent} onClick={e => e.stopPropagation()}><div style={S.modalHeader}><span style={{ fontSize: 16, fontWeight: 600 }}>Detail anggota</span><button onClick={() => setDetail(null)} style={S.closeBtn}>✕</button></div><div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 16 }}><div style={S.avatar(m.status === "aktif" ? "#2563EB" : "#94A3B8")}>{m.nama.split(" ").map(n => n[0]).join("").substring(0,2)}</div><div><div style={{ fontWeight: 600, fontSize: 15 }}>{m.nama}</div><div style={{ fontSize: 12, color: "#64748B" }}>{m.id}</div></div><span style={S.badge(m.status)}>{m.status}</span></div>{[["No. HP", m.hp], ["Alamat", m.alamat], ["Tgl masuk", m.tglMasuk], ["Poin", m.poin||0], ["SHU", `Rp ${fmt(shu)}`]].map(([l,v]) => (<div key={l} style={{ display: "flex", justifyContent: "space-between", padding: "6px 0", borderBottom: "1px solid #F1F5F9", fontSize: 13 }}><span style={{ color: "#64748B" }}>{l}</span><span style={{ fontWeight: 500 }}>{v}</span></div>))}<div style={S.sectionTitle}>Simpanan pokok</div><div style={{ ...S.card, display: "flex", justifyContent: "space-between", alignItems: "center" }}><span style={{ fontWeight: 500, color: pokok?.lunas ? "#16A34A" : "#DC2626" }}>{pokok?.lunas ? `Lunas (${pokok.tgl})` : "Belum"}</span>{!pokok?.lunas && <button style={S.btnOutline} onClick={() => bayarPokok(m.id)}>Bayar</button>}</div><div style={S.sectionTitle}>Simpanan wajib</div><div style={S.card}><div style={{ display: "flex", flexWrap: "wrap", gap: 4 }}>{BULAN.map((b,i) => (<div key={i} style={S.monthDot(wajib.includes(i) ? "paid" : i > currentMonth ? "future" : "unpaid")} onClick={() => i<=currentMonth && toggleWajib(m.id,i)}>{b}</div>))}</div><div style={{ fontSize: 12, color: "#64748B", marginTop: 8 }}>Total: Rp {fmt(wajib.length*SIMPANAN_WAJIB)}</div></div><div style={{ display: "flex", gap: 8, marginTop: 16 }}><button style={{ ...S.btnOutline, flex: 1 }} onClick={() => { setDetail(null); setEditM(m); }}>Edit</button><button style={{ ...S.btn(m.status === "aktif" ? "#DC2626" : "#16A34A"), flex: 1, fontSize: 13 }} onClick={() => { toggleStatus(m.id); setDetail(null); }}>{m.status === "aktif" ? "Nonaktifkan" : "Aktifkan"}</button></div></div></div>); })()}
  </>);
}
