import { useState } from "react";
import { useData } from "../context/DataContext";
import { POIN_PER_RP, STOK_WARNING, fmt, tglNow } from "../config";
import S from "../styles";

export default function Kasir() {
  const { barang, transaksi, activeMembers, lowStock, prosesTransaksi, addBarang, updateBarang, restokBarang } = useData();
  const [sub, setSub] = useState("kasir");
  const [searchB, setSearchB] = useState("");
  const [cart, setCart] = useState([]);
  const [bayarNom, setBayarNom] = useState("");
  const [pembeliType, setPembeliType] = useState("umum");
  const [pembeliId, setPembeliId] = useState("");
  const [pembeliNama, setPembeliNama] = useState("");
  const [showStruk, setShowStruk] = useState(null);
  const [showHistori, setShowHistori] = useState(false);
  const [showBarangForm, setShowBarangForm] = useState(false);
  const [editB, setEditB] = useState(null);
  const [showRestok, setShowRestok] = useState(null);

  const cartTotal = cart.reduce((s, c) => s + c.hargaJual * c.qty, 0);
  const cartCount = cart.reduce((s, c) => s + c.qty, 0);
  const todayTrx = transaksi.filter(t => t.tgl === tglNow());
  const todayOmzet = todayTrx.reduce((s, t) => s + t.total, 0);
  const filtered = barang.filter(b => b.nama.toLowerCase().includes(searchB.toLowerCase()) || b.kode.toLowerCase().includes(searchB.toLowerCase()));

  const addToCart = (item) => { if (item.stok <= 0) return; const ex = cart.find(c => c.id === item.id); if (ex) { if (ex.qty >= item.stok) return; setCart(cart.map(c => c.id === item.id ? { ...c, qty: c.qty + 1 } : c)); } else setCart([...cart, { ...item, qty: 1 }]); };
  const updateQty = (id, d) => { const item = barang.find(b => b.id === id); setCart(cart.map(c => { if (c.id !== id) return c; const nq = c.qty + d; if (nq <= 0) return null; if (nq > item.stok) return c; return { ...c, qty: nq }; }).filter(Boolean)); };

  const handleBayar = () => {
    const nom = parseInt(bayarNom.replace(/\D/g,"")) || 0;
    if (nom < cartTotal) return;
    const pembeli = pembeliType === "anggota" ? { type: "anggota", id: pembeliId, nama: activeMembers.find(m => m.id === pembeliId)?.nama || "" } : { type: "umum", id: null, nama: pembeliNama || "Umum" };
    const trx = prosesTransaksi(cart, nom, pembeli);
    setCart([]); setBayarNom(""); setPembeliType("umum"); setPembeliId(""); setPembeliNama(""); setShowStruk(trx);
  };

  return (<>
    <div style={{ display: "flex", gap: 0, marginBottom: 12, borderBottom: "1px solid #E2E8F0" }}><button style={S.tabBtn(sub === "kasir")} onClick={() => setSub("kasir")}>Kasir</button><button style={S.tabBtn(sub === "stok")} onClick={() => setSub("stok")}>Stok</button></div>

    {sub === "kasir" && (<>
      <div style={{ display: "flex", gap: 8, marginBottom: 12 }}><div style={S.statCard}><div style={{ fontSize: 11, color: "#64748B" }}>Transaksi</div><div style={{ fontSize: 20, fontWeight: 700, color: "#2563EB" }}>{todayTrx.length}</div></div><div style={S.statCard}><div style={{ fontSize: 11, color: "#64748B" }}>Omzet hari ini</div><div style={{ fontSize: 20, fontWeight: 700, color: "#16A34A" }}>Rp {fmt(todayOmzet)}</div></div></div>
      <div style={{ display: "flex", gap: 8, marginBottom: 12 }}><input style={{ ...S.input, flex: 1 }} placeholder="Cari barang..." value={searchB} onChange={e => setSearchB(e.target.value)} /><button style={{ ...S.btnSm("#64748B"), whiteSpace: "nowrap" }} onClick={() => setShowHistori(true)}>Riwayat</button></div>
      {searchB && <div style={{ marginBottom: 12 }}>{filtered.slice(0,6).map(b => (<div key={b.id} style={{ ...S.card, display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><div style={{ fontSize: 13, fontWeight: 600 }}>{b.nama}</div><div style={{ fontSize: 12, color: "#64748B" }}>Rp {fmt(b.hargaJual)} · Stok: {b.stok}</div></div><button style={S.btnSm(b.stok > 0 ? "#2563EB" : "#CBD5E1")} onClick={() => addToCart(b)} disabled={b.stok<=0}>+ Tambah</button></div>))}</div>}
      {cart.length > 0 && (<>
        <div style={S.sectionTitle}>Keranjang ({cartCount})</div>
        {cart.map(c => (<div key={c.id} style={{ ...S.card, display: "flex", justifyContent: "space-between", alignItems: "center" }}><div style={{ flex: 1 }}><div style={{ fontSize: 13, fontWeight: 600 }}>{c.nama}</div><div style={{ fontSize: 12, color: "#64748B" }}>Rp {fmt(c.hargaJual)} × {c.qty} = <span style={{ color: "#2563EB", fontWeight: 600 }}>Rp {fmt(c.hargaJual*c.qty)}</span></div></div><div style={{ display: "flex", alignItems: "center", gap: 6 }}><button style={S.qtyBtn} onClick={() => updateQty(c.id,-1)}>−</button><span style={{ fontSize: 14, fontWeight: 600, minWidth: 20, textAlign: "center" }}>{c.qty}</span><button style={S.qtyBtn} onClick={() => updateQty(c.id,1)}>+</button><button style={{ ...S.qtyBtn, background: "#DC2626", marginLeft: 4, fontSize: 12 }} onClick={() => setCart(cart.filter(x => x.id !== c.id))}>✕</button></div></div>))}
        <div style={{ ...S.card, background: "#F0F9FF", border: "1px solid #BAE6FD" }}>
          <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 8 }}>Pembeli</div>
          <div style={{ display: "flex", gap: 8, marginBottom: 8 }}><button style={S.btnSm(pembeliType === "anggota" ? "#2563EB" : "#CBD5E1")} onClick={() => setPembeliType("anggota")}>Anggota</button><button style={S.btnSm(pembeliType === "umum" ? "#2563EB" : "#CBD5E1")} onClick={() => setPembeliType("umum")}>Bukan anggota</button></div>
          {pembeliType === "anggota" ? <select style={S.input} value={pembeliId} onChange={e => setPembeliId(e.target.value)}><option value="">-- Pilih anggota --</option>{activeMembers.map(m => <option key={m.id} value={m.id}>{m.nama} ({m.id})</option>)}</select> : <input style={S.input} placeholder="Nama pembeli (opsional)" value={pembeliNama} onChange={e => setPembeliNama(e.target.value)} />}
          {pembeliType === "anggota" && pembeliId && <div style={{ fontSize: 11, color: "#16A34A", marginTop: 6 }}>+{Math.floor(cartTotal/POIN_PER_RP)} poin</div>}
        </div>
        <div style={{ ...S.card, background: "#EFF6FF", border: "1px solid #BFDBFE" }}>
          <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 10 }}><span style={{ fontSize: 15, fontWeight: 600 }}>Total</span><span style={{ fontSize: 18, fontWeight: 700, color: "#2563EB" }}>Rp {fmt(cartTotal)}</span></div>
          <input style={{ ...S.input, marginBottom: 8 }} placeholder="Nominal bayar" value={bayarNom} onChange={e => setBayarNom(e.target.value)} type="number" />
          {bayarNom && parseInt(bayarNom) >= cartTotal && <div style={{ fontSize: 13, color: "#16A34A", fontWeight: 500, marginBottom: 8 }}>Kembalian: Rp {fmt(parseInt(bayarNom)-cartTotal)}</div>}
          <button style={S.btn(parseInt(bayarNom||0) >= cartTotal && (pembeliType === "umum" || pembeliId) ? "#16A34A" : "#CBD5E1")} onClick={handleBayar} disabled={parseInt(bayarNom||0) < cartTotal || (pembeliType === "anggota" && !pembeliId)}>Proses pembayaran</button>
        </div>
      </>)}
      {cart.length === 0 && !searchB && <div style={{ textAlign: "center", padding: "40px 20px", color: "#94A3B8" }}><div style={{ fontSize: 36, marginBottom: 8 }}>🛒</div><div style={{ fontSize: 14, color: "#64748B" }}>Ketik nama barang untuk mulai</div></div>}
    </>)}

    {sub === "stok" && (<>
      <div style={{ display: "flex", gap: 8, marginBottom: 12 }}><div style={S.statCard}><div style={{ fontSize: 11, color: "#64748B" }}>Jenis</div><div style={{ fontSize: 20, fontWeight: 700, color: "#2563EB" }}>{barang.length}</div></div><div style={S.statCard}><div style={{ fontSize: 11, color: "#64748B" }}>Stok rendah</div><div style={{ fontSize: 20, fontWeight: 700, color: lowStock.length > 0 ? "#DC2626" : "#16A34A" }}>{lowStock.length}</div></div></div>
      {lowStock.length > 0 && (<><div style={S.sectionTitle}>⚠ Perlu restok</div>{lowStock.map(b => (<div key={b.id} style={{ ...S.card, display: "flex", justifyContent: "space-between", alignItems: "center", borderLeft: "3px solid #F59E0B" }}><div><div style={{ fontSize: 13, fontWeight: 600 }}>{b.nama}</div><div style={{ fontSize: 12, color: "#64748B" }}>Stok: <span style={{ color: "#DC2626", fontWeight: 600 }}>{b.stok}</span></div></div><button style={S.btnSm("#F59E0B")} onClick={() => setShowRestok(b)}>Restok</button></div>))}</>)}
      <div style={S.sectionTitle}>Semua barang</div>
      {barang.map(b => (<div key={b.id} style={{ ...S.card, display: "flex", justifyContent: "space-between", alignItems: "center" }}><div style={{ flex: 1 }}><div style={{ fontSize: 13, fontWeight: 600 }}>{b.nama}</div><div style={{ fontSize: 11, color: "#64748B" }}>{b.kode} · {b.kategori}</div><div style={{ fontSize: 12, marginTop: 2 }}><span style={{ color: "#64748B" }}>Beli: Rp {fmt(b.hargaBeli)}</span> · <span style={{ color: "#2563EB", fontWeight: 500 }}>Jual: Rp {fmt(b.hargaJual)}</span></div></div><div style={{ textAlign: "right" }}><div style={{ fontSize: 16, fontWeight: 700, color: b.stok <= STOK_WARNING ? "#DC2626" : "#1E293B" }}>{b.stok}</div><div style={{ display: "flex", gap: 4, marginTop: 4 }}><button style={S.btnSm("#64748B")} onClick={() => setEditB(b)}>Edit</button><button style={S.btnSm("#F59E0B")} onClick={() => setShowRestok(b)}>+Stok</button></div></div></div>))}
      <button style={S.fab} onClick={() => setShowBarangForm(true)}>+</button>
    </>)}

    {/* MODALS */}
    {showBarangForm && (() => { const F = () => { const [f, setF] = useState({ kode: "", nama: "", kategori: "Sembako", hargaBeli: "", hargaJual: "", stok: "" }); const [err, setErr] = useState(""); return (<div style={S.modal} onClick={() => setShowBarangForm(false)}><div style={S.modalContent} onClick={e => e.stopPropagation()}><div style={S.modalHeader}><span style={{ fontSize: 16, fontWeight: 600 }}>Tambah barang</span><button onClick={() => setShowBarangForm(false)} style={S.closeBtn}>✕</button></div><div style={{ display: "flex", flexDirection: "column", gap: 10 }}><input style={S.input} placeholder="Kode" value={f.kode} onChange={e => setF({...f, kode: e.target.value})} /><input style={S.input} placeholder="Nama barang" value={f.nama} onChange={e => { setF({...f, nama: e.target.value}); setErr(""); }} /><select style={S.input} value={f.kategori} onChange={e => setF({...f, kategori: e.target.value})}>{["Sembako","Bumbu","Makanan","Minuman","Kebersihan","Lainnya"].map(k => <option key={k}>{k}</option>)}</select><div style={{ display: "flex", gap: 8 }}><input style={S.input} placeholder="H. beli" type="number" value={f.hargaBeli} onChange={e => setF({...f, hargaBeli: e.target.value})} /><input style={S.input} placeholder="H. jual" type="number" value={f.hargaJual} onChange={e => setF({...f, hargaJual: e.target.value})} /></div><input style={S.input} placeholder="Stok awal" type="number" value={f.stok} onChange={e => setF({...f, stok: e.target.value})} />{err && <p style={{ color: "#DC2626", fontSize: 12, margin: 0 }}>{err}</p>}<button style={S.btn()} onClick={() => { if (!f.nama.trim()) { setErr("Nama wajib"); return; } if (!f.hargaJual) { setErr("Harga jual wajib"); return; } addBarang({ ...f, hargaBeli: parseInt(f.hargaBeli)||0, hargaJual: parseInt(f.hargaJual)||0, stok: parseInt(f.stok)||0 }); setShowBarangForm(false); }}>Simpan</button></div></div></div>); }; return <F />; })()}
    {editB && (() => { const F = () => { const [f, setF] = useState(editB); return (<div style={S.modal} onClick={() => setEditB(null)}><div style={S.modalContent} onClick={e => e.stopPropagation()}><div style={S.modalHeader}><span style={{ fontSize: 16, fontWeight: 600 }}>Edit barang</span><button onClick={() => setEditB(null)} style={S.closeBtn}>✕</button></div><div style={{ display: "flex", flexDirection: "column", gap: 10 }}><input style={S.input} placeholder="Kode" value={f.kode} onChange={e => setF({...f, kode: e.target.value})} /><input style={S.input} placeholder="Nama" value={f.nama} onChange={e => setF({...f, nama: e.target.value})} /><select style={S.input} value={f.kategori} onChange={e => setF({...f, kategori: e.target.value})}>{["Sembako","Bumbu","Makanan","Minuman","Kebersihan","Lainnya"].map(k => <option key={k}>{k}</option>)}</select><div style={{ display: "flex", gap: 8 }}><input style={S.input} placeholder="H. beli" type="number" value={f.hargaBeli} onChange={e => setF({...f, hargaBeli: e.target.value})} /><input style={S.input} placeholder="H. jual" type="number" value={f.hargaJual} onChange={e => setF({...f, hargaJual: e.target.value})} /></div><button style={S.btn()} onClick={() => { updateBarang({ ...f, hargaBeli: parseInt(f.hargaBeli)||0, hargaJual: parseInt(f.hargaJual)||0 }); setEditB(null); }}>Simpan</button></div></div></div>); }; return <F />; })()}
    {showRestok && (() => { const F = () => { const [qty, setQty] = useState(""); const [biaya, setBiaya] = useState(""); return (<div style={S.modal} onClick={() => setShowRestok(null)}><div style={{ ...S.modalContent, paddingBottom: 24 }} onClick={e => e.stopPropagation()}><div style={S.modalHeader}><span style={{ fontSize: 16, fontWeight: 600 }}>Restok: {showRestok.nama}</span><button onClick={() => setShowRestok(null)} style={S.closeBtn}>✕</button></div><div style={{ fontSize: 13, color: "#64748B", marginBottom: 12 }}>Stok: <strong>{showRestok.stok}</strong></div><input style={{ ...S.input, marginBottom: 8 }} placeholder="Jumlah" type="number" value={qty} onChange={e => setQty(e.target.value)} /><input style={{ ...S.input, marginBottom: 10 }} placeholder="Total biaya (Rp)" type="number" value={biaya} onChange={e => setBiaya(e.target.value)} /><button style={S.btn()} onClick={() => { if (parseInt(qty)>0) { restokBarang(showRestok.id, parseInt(qty), parseInt(biaya)||0); setShowRestok(null); } }}>Tambah</button></div></div>); }; return <F />; })()}
    {showStruk && (<div style={S.modal} onClick={() => setShowStruk(null)}><div style={{ ...S.modalContent, textAlign: "center" }} onClick={e => e.stopPropagation()}><div style={{ fontSize: 24, color: "#16A34A", marginBottom: 8 }}>✓</div><div style={{ fontSize: 18, fontWeight: 600 }}>Transaksi berhasil</div><div style={{ fontSize: 12, color: "#64748B", marginBottom: 4 }}>{showStruk.tgl} · {showStruk.waktu}</div>{showStruk.pembeli && <div style={{ fontSize: 12, color: "#2563EB", marginBottom: 12 }}>{showStruk.pembeli.nama}{showStruk.pembeli.type === "anggota" ? ` (+${Math.floor(showStruk.total/POIN_PER_RP)} poin)` : ""}</div>}<div style={{ textAlign: "left", borderTop: "1px dashed #CBD5E1", paddingTop: 12 }}>{showStruk.items.map((it,i) => (<div key={i} style={{ display: "flex", justifyContent: "space-between", fontSize: 13, padding: "4px 0" }}><span>{it.nama} ×{it.qty}</span><span style={{ fontWeight: 500 }}>Rp {fmt(it.subtotal)}</span></div>))}<div style={{ borderTop: "1px dashed #CBD5E1", marginTop: 8, paddingTop: 8 }}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 15, fontWeight: 700 }}><span>Total</span><span>Rp {fmt(showStruk.total)}</span></div><div style={{ display: "flex", justifyContent: "space-between", fontSize: 13, color: "#64748B", marginTop: 4 }}><span>Bayar</span><span>Rp {fmt(showStruk.bayar)}</span></div><div style={{ display: "flex", justifyContent: "space-between", fontSize: 13, color: "#16A34A", fontWeight: 500 }}><span>Kembalian</span><span>Rp {fmt(showStruk.kembalian)}</span></div></div></div><button style={{ ...S.btn(), marginTop: 16 }} onClick={() => setShowStruk(null)}>Tutup</button></div></div>)}
    {showHistori && (<div style={S.modal} onClick={() => setShowHistori(false)}><div style={S.modalContent} onClick={e => e.stopPropagation()}><div style={S.modalHeader}><span style={{ fontSize: 16, fontWeight: 600 }}>Riwayat transaksi</span><button onClick={() => setShowHistori(false)} style={S.closeBtn}>✕</button></div>{transaksi.length === 0 ? <div style={{ textAlign: "center", padding: 30, color: "#94A3B8", fontSize: 13 }}>Belum ada</div> : transaksi.slice(0,20).map(t => (<div key={t.id} style={{ ...S.card, cursor: "pointer" }} onClick={() => { setShowHistori(false); setShowStruk(t); }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><div style={{ fontSize: 13, fontWeight: 600 }}>{t.tgl} · {t.waktu}</div><div style={{ fontSize: 11, color: "#64748B" }}>{t.pembeli?.nama || "—"} · {t.items.length} item</div></div><div style={{ fontSize: 15, fontWeight: 700, color: "#2563EB" }}>Rp {fmt(t.total)}</div></div></div>))}</div></div>)}
  </>);
}
