const S = {
  app: { fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif', maxWidth: 480, margin: "0 auto", minHeight: "100vh", display: "flex", flexDirection: "column", background: "#FDF8F0", color: "#1E293B" },
  header: { background: "#2563EB", color: "white", padding: "14px 16px", display: "flex", justifyContent: "space-between", alignItems: "center" },
  headerTitle: { fontSize: 18, fontWeight: 600, letterSpacing: 0.5 },
  content: { flex: 1, padding: "12px 12px 80px", overflowY: "auto" },
  bottomNav: { position: "fixed", bottom: 0, left: "50%", transform: "translateX(-50%)", width: "100%", maxWidth: 480, display: "grid", background: "white", borderTop: "1px solid #E2E8F0", paddingBottom: 8, zIndex: 10 },
  navItem: (a) => ({ display: "flex", flexDirection: "column", alignItems: "center", gap: 2, padding: "8px 0 4px", fontSize: 11, color: a ? "#2563EB" : "#94A3B8", cursor: "pointer", background: "none", border: "none", fontWeight: a ? 600 : 400 }),
  card: { background: "white", borderRadius: 12, padding: "12px 14px", border: "1px solid #E8E4DC", marginBottom: 8 },
  statCard: { background: "white", borderRadius: 10, padding: "10px 14px", border: "1px solid #E8E4DC", flex: 1 },
  btn: (c = "#2563EB") => ({ background: c, color: c === "transparent" ? "#2563EB" : "white", border: c === "transparent" ? "1.5px solid #2563EB" : "none", borderRadius: 8, padding: "10px 16px", fontSize: 14, fontWeight: 500, cursor: "pointer", width: "100%" }),
  btnSm: (c = "#2563EB") => ({ background: c, color: "white", border: "none", borderRadius: 6, padding: "6px 12px", fontSize: 12, fontWeight: 500, cursor: "pointer" }),
  btnOutline: { background: "transparent", color: "#2563EB", border: "1.5px solid #2563EB", borderRadius: 8, padding: "8px 14px", fontSize: 13, fontWeight: 500, cursor: "pointer" },
  input: { width: "100%", padding: "10px 12px", borderRadius: 8, border: "1px solid #CBD5E1", fontSize: 14, boxSizing: "border-box", background: "white", color: "#1E293B" },
  badge: (t) => ({ fontSize: 11, padding: "3px 10px", borderRadius: 12, fontWeight: 500, ...(t === "aktif" || t === "masuk" ? { background: "#DCFCE7", color: "#166534" } : t === "non-aktif" || t === "keluar" ? { background: "#FEE2E2", color: "#991B1B" } : { background: "#FEF3C7", color: "#92400E" }) }),
  fab: { position: "fixed", bottom: 76, right: "calc(50% - 210px)", width: 48, height: 48, borderRadius: "50%", background: "#2563EB", color: "white", border: "none", fontSize: 24, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 2px 8px rgba(37,99,235,0.3)", zIndex: 5 },
  sectionTitle: { fontSize: 13, fontWeight: 600, color: "#64748B", marginBottom: 8, marginTop: 12 },
  avatar: (c = "#2563EB") => ({ width: 38, height: 38, borderRadius: "50%", background: c, color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 600, flexShrink: 0 }),
  monthDot: (s) => ({ width: 26, height: 22, borderRadius: 4, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 9, fontWeight: 600, cursor: s === "future" ? "default" : "pointer", ...(s === "paid" ? { background: "#DCFCE7", color: "#166534" } : s === "unpaid" ? { background: "#FEE2E2", color: "#991B1B" } : { background: "#F1F5F9", color: "#94A3B8" }) }),
  tabBtn: (a) => ({ flex: 1, padding: "8px 0", textAlign: "center", fontSize: 13, fontWeight: a ? 600 : 400, color: a ? "#2563EB" : "#64748B", background: "none", border: "none", borderBottom: `2px solid ${a ? "#2563EB" : "transparent"}`, cursor: "pointer" }),
  modal: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.4)", display: "flex", alignItems: "flex-end", justifyContent: "center", zIndex: 20 },
  modalContent: { background: "#FDF8F0", borderRadius: "16px 16px 0 0", width: "100%", maxWidth: 480, maxHeight: "85vh", overflowY: "auto", padding: "20px 16px 32px" },
  modalHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  closeBtn: { background: "none", border: "none", fontSize: 20, cursor: "pointer", color: "#64748B" },
  qtyBtn: { width: 28, height: 28, borderRadius: 6, background: "#2563EB", color: "white", border: "none", fontSize: 16, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" },
};
export default S;
